version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV
      - DATABASE_URL
    networks:
      - mafalda

  frontend:
    build:
      dockerfile: Dockerfile_frontend
    container_name: frontend
    command: "npm run dev"
    ports:
      - "5173:5173"
    networks:
      - mafalda

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - mafalda

volumes:
  my-db:
  dbdata6:

networks:
  mafalda:
    driver: bridge

 