name: PI_MANAGER

on:
  push:
    branches:
      - "main"
      - "working_area"
    
  pull_request:
    branches:
      - "main"
     

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PI_MANAGER

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create test.env file
       
        run: |
          cd server
          echo "MONGO_URI"="mongodb://localhost:27017" >> test.env
          echo "DATABASE"="raspberrypi_test" >> test.env
          echo "NODE_ENV"="test" >> test.env
          echo "PORT"="4001" >> test.env
          echo "PAIR_PASSWORD"="testPassword" >> test.env
          echo "JWT_SECRET"="74310907898vnmrbmvbipc734086n3e65jblppl4c9n" >> .env

         

      - name: Print .env file
        run: |
          echo "Printing test.env:"
          cat server/test.env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-port: 27017

      - name: Build NODE APP
        run: |
          npm ci
          npm run eslint
          npm run build
        working-directory: ./server

      - name: Run mongo_test
        run: |
          npm run test_api
        working-directory: ./server
      - name: Run domain_test
        run: |
          npm run test_domain
        working-directory: ./server
      - name: Run infrastructure_test
        run: |
          npm run test_infrastructure
        working-directory: ./server

