name: PI_MANAGER

on:
  push:
    branches:
      - "main"
      - "working_area"
    
  pull_request:
    branches:
      - "main"
     

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PI_MANAGER

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create .env file
       
        run: |
          cd server
          echo "NODE_ENV"="test_mode" >> .env
         
      - name: Print .env file
        run: |
          echo "Printing .env:"
          cat server/.env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-port: 27017

      - name: Build NODE APP
        run: |
          npm ci
          npm run eslint
          npm run build
        working-directory: ./server

      - name: Run api file tests
        run: |
          npm run test_api_file
        working-directory: ./server
      - name: Run api database tests
        run: |
          npm run test_api_database
        working-directory: ./server
      - name: Run domain_test
        run: |
          npm run test_domain
        working-directory: ./server
      - name: Run infrastructure_test
        run: |
          npm run test_infrastructure
        working-directory: ./server

